codes=[
    { code : "A00", description : "Cholera", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A000", description : "Cholera due to Vibrio cholerae 01, biovar cholerae", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A001", description : "Cholera due to Vibrio cholerae 01, biovar eltor", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A009", description : "Cholera, unspecified", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A01", description : "Typhoid and paratyphoid fevers", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A010", description : "Typhoid fever", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A011", description : "Paratyphoid fever A", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A012", description : "Paratyphoid fever B", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A013", description : "Paratyphoid fever C", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A014", description : "Paratyphoid fever, unspecified", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A02", description : "Other salmonella infections", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A020", description : "Salmonella enteritis", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A021", description : "Salmonella septicaemia", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A022", description : "Localized salmonella infections", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A028", description : "Other specified salmonella infections", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A029", description : "Salmonella infection, unspecified", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A03", description : "Shigellosis", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A030", description : "Shigellosis due to Shigella dysenteriae", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A031", description : "Shigellosis due to Shigella flexneri", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A032", description : "Shigellosis due to Shigella boydii", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A033", description : "Shigellosis due to Shigella sonnei", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A038", description : "Other shigellosis", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A039", description : "Shigellosis, unspecified", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A04", description : "Other bacterial intestinal infections", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A040", description : "Enteropathogenic Escherichia coli infection", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A041", description : "Enterotoxigenic Escherichia coli infection", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A042", description : "Enteroinvasive Escherichia coli infection", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A043", description : "Enterohaemorrhagic Escherichia coli infection", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A044", description : "Other intestinal Escherichia coli infections", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A045", description : "Campylobacter enteritis", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A046", description : "Enteritis due to Yersinia enterocolitica", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A047", description : "Enterocolitis due to Clostridium difficile", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A048", description : "Other specified bacterial intestinal infections", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A049", description : "Bacterial intestinal infection, unspecified", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A05", description : "Other bacterial foodborne intoxications, not elsewhere classified", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A050", description : "Foodborne staphylococcal intoxication", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A051", description : "Botulism", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A052", description : "Foodborne Clostridium perfringens [Clostridium welchii] intoxication", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A053", description : "Foodborne Vibrio parahaemolyticus intoxication", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A054", description : "Foodborne Bacillus cereus intoxication", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A058", description : "Other specified bacterial foodborne intoxications", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A059", description : "Bacterial foodborne intoxication, unspecified", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A06", description : "Amoebiasis", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A060", description : "Acute amoebic dysentery", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A061", description : "Chronic intestinal amoebiasis", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A062", description : "Amoebic nondysenteric colitis", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A063", description : "Amoeboma of intestine", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A064", description : "Amoebic liver abscess", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A065", description : "Amoebic lung abscess", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A066", description : "Amoebic brain abscess", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A067", description : "Cutaneous amoebiasis", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A068", description : "Amoebic infection of other sites", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A069", description : "Amoebiasis, unspecified", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A07", description : "Other protozoal intestinal diseases", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A070", description : "Balantidiasis", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A071", description : "Giardiasis [lambliasis]", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A072", description : "Cryptosporidiosis", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A073", description : "Isosporiasis", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A078", description : "Other specified protozoal intestinal diseases", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A079", description : "Protozoal intestinal disease, unspecified", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A08", description : "Viral and other specified intestinal infections", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A080", description : "Rotaviral enteritis", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A081", description : "Acute gastroenteropathy due to Norwalk agent", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A082", description : "Adenoviral enteritis", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A083", description : "Other viral enteritis", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A084", description : "Viral intestinal infection, unspecified", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A085", description : "Other specified intestinal infections", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A09", description : "Diarrhoea and gastroenteritis of presumed infectious origin", block : "Intestinal infectious diseases", chapter : "Certain infectious and parasitic diseases"},
    { code : "A15", description : "Respiratory tuberculosis, bacteriologically and histologically confirmed", block : "Tuberculosis", chapter : "Certain infectious and parasitic diseases"},
    { code : "A150", description : "Tuberculosis of lung, confirmed by sputum microscopy with or without culture", block : "Tuberculosis", chapter : "Certain infectious and parasitic diseases"},
    { code : "A151", description : "Tuberculosis of lung, confirmed by culture only", block : "Tuberculosis", chapter : "Certain infectious and parasitic diseases"},
    { code : "A152", description : "Tuberculosis of lung, confirmed histologically", block : "Tuberculosis", chapter : "Certain infectious and parasitic diseases"},
    { code : "A153", description : "Tuberculosis of lung, confirmed by unspecified means", block : "Tuberculosis", chapter : "Certain infectious and parasitic diseases"},
    { code : "A154", description : "Tuberculosis of intrathoracic lymph nodes, confirmed bacteriologically and histologically", block : "Tuberculosis", chapter : "Certain infectious and parasitic diseases"},
    { code : "A155", description : "Tuberculosis of larynx, trachea and bronchus, confirmed bacteriologically and histologically", block : "Tuberculosis", chapter : "Certain infectious and parasitic diseases"},
    { code : "A156", description : "Tuberculous pleurisy, confirmed bacteriologically and histologically", block : "Tuberculosis", chapter : "Certain infectious and parasitic diseases"},
    { code : "A157", description : "Primary respiratory tuberculosis, confirmed bacteriologically and histologically", block : "Tuberculosis", chapter : "Certain infectious and parasitic diseases"},
    { code : "A158", description : "Other respiratory tuberculosis, confirmed bacteriologically and histologically", block : "Tuberculosis", chapter : "Certain infectious and parasitic diseases"},
    { code : "A159", description : "Respiratory tuberculosis unspecified, confirmed bacteriologically and histologically", block : "Tuberculosis", chapter : "Certain infectious and parasitic diseases"},
    { code : "A16", description : "Respiratory tuberculosis, not confirmed bacteriologically or histologically", block : "Tuberculosis", chapter : "Certain infectious and parasitic diseases"},
    { code : "A160", description : "Tuberculosis of lung, bacteriologically and histologically negative", block : "Tuberculosis", chapter : "Certain infectious and parasitic diseases"},
    { code : "A161", description : "Tuberculosis of lung, bacteriological and histological examination not done", block : "Tuberculosis", chapter : "Certain infectious and parasitic diseases"},
    { code : "A162", description : "Tuberculosis of lung, without mention of bacteriological or histological confirmation", block : "Tuberculosis", chapter : "Certain infectious and parasitic diseases"},
    { code : "A163", description : "Tuberculosis of intrathoracic lymph nodes, without mention of bacteriological or histological confirmation", block : "Tuberculosis", chapter : "Certain infectious and parasitic diseases"},
    { code : "A164", description : "Tuberculosis of larynx, trachea and bronchus, without mention of bacteriological or histological confirmation", block : "Tuberculosis", chapter : "Certain infectious and parasitic diseases"},
    { code : "A165", description : "Tuberculous pleurisy, without mention of bacteriological or histological confirmation", block : "Tuberculosis", chapter : "Certain infectious and parasitic diseases"},
    { code : "A167", description : "Primary respiratory tuberculosis without mention of bacteriological or histological confirmation", block : "Tuberculosis", chapter : "Certain infectious and parasitic diseases"},
    { code : "A168", description : "Other respiratory tuberculosis, without mention of bacteriological or histological confirmation", block : "Tuberculosis", chapter : "Certain infectious and parasitic diseases"},
    { code : "A169", description : "Respiratory tuberculosis unspecified, without mention of bacteriological or histological confirmation", block : "Tuberculosis", chapter : "Certain infectious and parasitic diseases"},
    { code : "A17", description : "Tuberculosis of nervous system", block : "Tuberculosis", chapter : "Certain infectious and parasitic diseases"},
    { code : "A170", description : "Tuberculous meningitis", block : "Tuberculosis", chapter : "Certain infectious and parasitic diseases"},
    { code : "A171", description : "Meningeal tuberculoma", block : "Tuberculosis", chapter : "Certain infectious and parasitic diseases"},
    { code : "A178", description : "Other tuberculosis of nervous system", block : "Tuberculosis", chapter : "Certain infectious and parasitic diseases"},
    { code : "A179", description : "Tuberculosis of nervous system, unspecified", block : "Tuberculosis", chapter : "Certain infectious and parasitic diseases"},
    { code : "A18", description : "Tuberculosis of other organs", block : "Tuberculosis", chapter : "Certain infectious and parasitic diseases"},
    { code : "A180", description : "Tuberculosis of bones and joints", block : "Tuberculosis", chapter : "Certain infectious and parasitic diseases"},
    { code : "A181", description : "Tuberculosis of genitourinary system", block : "Tuberculosis", chapter : "Certain infectious and parasitic diseases"},
    { code : "A182", description : "Tuberculous peripheral lymphadenopathy", block : "Tuberculosis", chapter : "Certain infectious and parasitic diseases"},
    { code : "A183", description : "Tuberculosis of intestines, peritoneum and mesenteric glands", block : "Tuberculosis", chapter : "Certain infectious and parasitic diseases"}
    ]